export const searchResult = {
  results: [
    {
      id: 631814,
      title: "$50,000 Burger",
      image: "https://spoonacular.com/recipeImages/631814-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 642539,
      title: "Falafel Burger",
      image: "https://spoonacular.com/recipeImages/642539-312x231.png",
      imageType: "png",
    },
    {
      id: 663050,
      title: "Tex-Mex Burger",
      image: "https://spoonacular.com/recipeImages/663050-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 622825,
      title: "Tortilla Burger Loco Vaca",
      image: "https://spoonacular.com/recipeImages/622825-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 663357,
      title: "The Unagi Burger",
      image: "https://spoonacular.com/recipeImages/663357-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 663252,
      title: "The Blarney Burger",
      image: "https://spoonacular.com/recipeImages/663252-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 651190,
      title: "Masala-Tofu Burger",
      image: "https://spoonacular.com/recipeImages/651190-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 663209,
      title: "The Benedict Burger",
      image: "https://spoonacular.com/recipeImages/663209-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 650181,
      title: "Little Italy Burger",
      image: "https://spoonacular.com/recipeImages/650181-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 637631,
      title: "Cheesy Bacon Burger with Spicy Chipotle Aiolo Sauce",
      image: "https://spoonacular.com/recipeImages/637631-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 638771,
      title: "Chipotle-Salsa Burger",
      image: "https://spoonacular.com/recipeImages/638771-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1697575,
      title: "Crispy Chicken Burger",
      image: "https://spoonacular.com/recipeImages/1697575-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 657243,
      title: "Pumpkin Almond Burger Patties",
      image: "https://spoonacular.com/recipeImages/657243-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 650377,
      title: "Low Carb Brunch Burger",
      image: "https://spoonacular.com/recipeImages/650377-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 780000,
      title: "Chicken Avocado Burger (Whole 30, PALEO, & Simple Fit Forty)",
      image: "https://spoonacular.com/recipeImages/780000-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632342,
      title: "An American Beef Burger",
      image: "https://spoonacular.com/recipeImages/632342-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 649141,
      title: "La Bella Italian Turkey Burger",
      image: "https://spoonacular.com/recipeImages/649141-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 775621,
      title: "Gorgonzola & Grilled Peach Burger",
      image: "https://spoonacular.com/recipeImages/775621-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 635345,
      title: "Blue Cheese and Mushroom Turkey Burger",
      image: "https://spoonacular.com/recipeImages/635345-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 801377,
      title: "Chicken Parmesan Patty- Eat As A Burger OR On Pasta",
      image: "https://spoonacular.com/recipeImages/801377-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 664011,
      title: "Turkey Burgers",
      image: "https://spoonacular.com/recipeImages/664011-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 642540,
      title: "Falafel Burgers",
      image: "https://spoonacular.com/recipeImages/642540-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 648303,
      title: "Itty Bitty Burgers",
      image: "https://spoonacular.com/recipeImages/648303-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 635350,
      title: "Blue Cheese Burgers",
      image: "https://spoonacular.com/recipeImages/635350-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 642695,
      title: "Feta Stuffed Burgers",
      image: "https://spoonacular.com/recipeImages/642695-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 650235,
      title: "Loaded Turkey Burgers",
      image: "https://spoonacular.com/recipeImages/650235-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 991010,
      title: "Chicken Ranch Burgers",
      image: "https://spoonacular.com/recipeImages/991010-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 649940,
      title: "Lentil Veggie Burgers",
      image: "https://spoonacular.com/recipeImages/649940-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 649182,
      title: "Lamb and Bacon Burgers",
      image: "https://spoonacular.com/recipeImages/649182-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632300,
      title: "Amazing Chicken Burgers",
      image: "https://spoonacular.com/recipeImages/632300-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1096267,
      title: "Turkey Burgers with Slaw",
      image: "https://spoonacular.com/recipeImages/1096267-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 647296,
      title: "Honey Wheat Hamburger Buns",
      image: "https://spoonacular.com/recipeImages/647296-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 644835,
      title: "Gluten Free Hamburger Buns",
      image: "https://spoonacular.com/recipeImages/644835-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 638566,
      title: "Chili Lime Chicken Burgers",
      image: "https://spoonacular.com/recipeImages/638566-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1487865,
      title: "Easy Cheeseburger Casserole",
      image: "https://spoonacular.com/recipeImages/1487865-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 638497,
      title: "Chickpea and Veggie Burgers",
      image: "https://spoonacular.com/recipeImages/638497-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 637488,
      title: "Chavrie Stuffed Turkey Burgers",
      image: "https://spoonacular.com/recipeImages/637488-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1095755,
      title: "Quinoa and Kidney Bean Burgers",
      image: "https://spoonacular.com/recipeImages/1095755-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 636595,
      title: "Butternut Squash Quinoa Burgers",
      image: "https://spoonacular.com/recipeImages/636595-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1096060,
      title: "Chicken Burgers with Spiced Rub",
      image: "https://spoonacular.com/recipeImages/1096060-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 649195,
      title: "Lamb Burgers With Tzatziki Sauce",
      image: "https://spoonacular.com/recipeImages/649195-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 664929,
      title: "Walnut Lentil Burgers with Tarragon",
      image: "https://spoonacular.com/recipeImages/664929-312x231.png",
      imageType: "png",
    },
    {
      id: 1095894,
      title: "Salmon Amaranth Burgers with Radish Slaw",
      image: "https://spoonacular.com/recipeImages/1095894-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 648663,
      title: "Just Julie’s BBQ Spicy Black Bean Burgers",
      image: "https://spoonacular.com/recipeImages/648663-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 659058,
      title: "Salmon Burgers With Roasted Red Pepper Aioli",
      image: "https://spoonacular.com/recipeImages/659058-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 635059,
      title: "Black Bean and Veggie Burgers with Corn Salsa",
      image: "https://spoonacular.com/recipeImages/635059-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 640266,
      title: "Crab and Shrimp Burgers With Garlic Grits Fries",
      image: "https://spoonacular.com/recipeImages/640266-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1095682,
      title: "Mini Zucchini Avocado Burgers",
      image: "https://spoonacular.com/recipeImages/1095682-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632874,
      title: "Asian Salmon Burgers With Tangy Ginger Lime Sauce",
      image: "https://spoonacular.com/recipeImages/632874-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 664080,
      title: "Turkey-Spinach Burgers With Sweet Soy-Ginger Sauce",
      image: "https://spoonacular.com/recipeImages/664080-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632502,
      title: "Apple Cheddar Turkey Burgers With Chipotle Yogurt Sauce",
      image: "https://spoonacular.com/recipeImages/632502-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 645608,
      title: "Grilled Turkey Burgers with Roasted Jalapeños and BBQ Sauce",
      image: "https://spoonacular.com/recipeImages/645608-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 638744,
      title: "Chipotle Cheese Stuffed Black Bean Burgers with Avocado Creme",
      image: "https://spoonacular.com/recipeImages/638744-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 645680,
      title:
        "Grilled Chuck Burgers with Extra Sharp Cheddar and Lemon Garlic Aioli",
      image: "https://spoonacular.com/recipeImages/645680-312x231.jpg",
      imageType: "jpg",
    },
  ],
  offset: 0,
  number: 100,
  totalResults: 54,
};

export const recipeInformation = {
  vegetarian: true,
  vegan: false,
  glutenFree: false,
  dairyFree: true,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 12,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 4,
  healthScore: 29,
  creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
  license: "CC BY 3.0",
  sourceName: "Foodista",
  pricePerServing: 164.17,
  extendedIngredients: [
    {
      id: 16058,
      aisle: "Canned and Jarred",
      image: "chickpeas.png",
      consistency: "SOLID",
      name: "chickpeas",
      nameClean: "canned chickpeas",
      original: "540 ml can of chickpeas, drained and rinsed",
      originalName: "chickpeas, drained and rinsed",
      amount: 540.0,
      unit: "ml",
      meta: ["drained and rinsed", "canned"],
      measures: {
        us: {
          amount: 2.282,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 540.0,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 12698,
      aisle: "Ethnic Foods;Health Foods",
      image: "tahini-paste.png",
      consistency: "SOLID",
      name: "tahini",
      nameClean: "tahini",
      original: "2 tsp tahini",
      originalName: "tahini",
      amount: 2.0,
      unit: "tsp",
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 2.0,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 1016168,
      aisle: "Condiments",
      image: "hot-sauce-or-tabasco.png",
      consistency: "LIQUID",
      name: "sriracha sauce",
      nameClean: "sriracha",
      original: "½ tsp sriracha sauce",
      originalName: "sriracha sauce",
      amount: 0.5,
      unit: "tsp",
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 11215,
      aisle: "Produce",
      image: "garlic.png",
      consistency: "SOLID",
      name: "garlic",
      nameClean: "garlic",
      original: "3 cloves garlic",
      originalName: "garlic",
      amount: 3.0,
      unit: "cloves",
      meta: [],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "cloves",
          unitLong: "cloves",
        },
        metric: {
          amount: 3.0,
          unitShort: "cloves",
          unitLong: "cloves",
        },
      },
    },
    {
      id: 10511297,
      aisle: "Produce",
      image: "parsley.jpg",
      consistency: "SOLID",
      name: "parsley",
      nameClean: "fresh parsley",
      original: "3 tbsp fresh parsley, roughly chopped",
      originalName: "fresh parsley, roughly chopped",
      amount: 3.0,
      unit: "tbsp",
      meta: ["fresh", "roughly chopped"],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 3.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 10011282,
      aisle: "Produce",
      image: "red-onion.png",
      consistency: "SOLID",
      name: "onion",
      nameClean: "red onion",
      original: "¼ large red onion, diced",
      originalName: "red onion, diced",
      amount: 0.25,
      unit: "large",
      meta: ["diced", "red"],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "large",
          unitLong: "larges",
        },
        metric: {
          amount: 0.25,
          unitShort: "large",
          unitLong: "larges",
        },
      },
    },
    {
      id: 4042,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "peanut-oil.jpg",
      consistency: "LIQUID",
      name: "peanut oil",
      nameClean: "peanut oil",
      original: "4 tbsp peanut oil",
      originalName: "peanut oil",
      amount: 4.0,
      unit: "tbsp",
      meta: [],
      measures: {
        us: {
          amount: 4.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 4.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 11206,
      aisle: "Produce",
      image: "cucumber.jpg",
      consistency: "SOLID",
      name: "cucumber",
      nameClean: "cucumber",
      original: "8 slices of cucumber",
      originalName: "cucumber",
      amount: 8.0,
      unit: "slices",
      meta: [],
      measures: {
        us: {
          amount: 8.0,
          unitShort: "slice",
          unitLong: "slices",
        },
        metric: {
          amount: 8.0,
          unitShort: "slice",
          unitLong: "slices",
        },
      },
    },
    {
      id: 11529,
      aisle: "Produce",
      image: "tomato.png",
      consistency: "SOLID",
      name: "tomato",
      nameClean: "tomato",
      original: "8 slices of tomato",
      originalName: "tomato",
      amount: 8.0,
      unit: "slices",
      meta: [],
      measures: {
        us: {
          amount: 8.0,
          unitShort: "slice",
          unitLong: "slices",
        },
        metric: {
          amount: 8.0,
          unitShort: "slice",
          unitLong: "slices",
        },
      },
    },
    {
      id: 18350,
      aisle: "Bakery/Bread",
      image: "hamburger-bun.jpg",
      consistency: "SOLID",
      name: "hamburger buns",
      nameClean: "hamburger bun",
      original:
        "4 hamburger buns (I used President's Choice multi-grain thins)",
      originalName:
        "hamburger buns (I used President's Choice multi-grain thins)",
      amount: 4.0,
      unit: "",
      meta: ["(I used President's Choice multi-grain thins)"],
      measures: {
        us: {
          amount: 4.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 4.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 93777,
      aisle: "Milk, Eggs, Other Dairy",
      image: "raita-or-tzaziki.png",
      consistency: "SOLID",
      name: "tzatziki",
      nameClean: "tzatziki",
      original: "Tzatziki for topping",
      originalName: "Tzatziki for topping",
      amount: 4.0,
      unit: "servings",
      meta: ["for topping"],
      measures: {
        us: {
          amount: 4.0,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 4.0,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
  ],
  id: 642539,
  title: "Falafel Burger",
  readyInMinutes: 45,
  servings: 4,
  sourceUrl: "https://www.foodista.com/recipe/DYNQRHMK/falafel-burger",
  image: "https://spoonacular.com/recipeImages/642539-556x370.png",
  imageType: "png",
  summary:
    'The recipe Falafel Burger is ready <b>in roughly 45 minutes</b> and is definitely an outstanding <b>dairy free and lacto ovo vegetarian</b> option for lovers of middl eastern food. This recipe serves 4 and costs $1.64 per serving. One portion of this dish contains approximately <b>11g of protein</b>, <b>23g of fat</b>, and a total of <b>400 calories</b>. It works well as a hor d\'oeuvre. 4 people were impressed by this recipe. If you have chickpeas, onion, parsley, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. Overall, this recipe earns a <b>tremendous spoonacular score of 82%</b>. <a href="https://spoonacular.com/recipes/falafel-burger-1371717">Falafel Burger</a>, <a href="https://spoonacular.com/recipes/falafel-burger-1220097">Falafel Burger</a>, and <a href="https://spoonacular.com/recipes/falafel-burger-1395111">Falafel Burger</a> are very similar to this recipe.',
  cuisines: ["Middle Eastern"],
  dishTypes: [
    "antipasti",
    "starter",
    "snack",
    "appetizer",
    "antipasto",
    "hor d'oeuvre",
  ],
  diets: ["dairy free", "lacto ovo vegetarian"],
  occasions: [],
  winePairing: {
    pairedWines: ["merlot", "malbec", "zinfandel"],
    pairingText:
      "Burger on the menu? Try pairing with Merlot, Malbec, and Zinfandel. Merlot will be perfectly adequate for a classic burger with standard toppings. Bolder toppings call for bolder wines, such as a malbec or peppery zinfandel. The Peju Province Merlot with a 4.5 out of 5 star rating seems like a good match. It costs about 38 dollars per bottle.",
    productMatches: [
      {
        id: 447335,
        title: "Peju Province Merlot",
        description:
          "The 2010 vintage showcases Merlot's stylish and alluring characteristics with vivid flavors of plum and black currant. Hints of anise and vanilla on the nose open up to complex, integrated layers of raspberry, cherry and cocoa flavors that impart a striking impression on the palate.",
        price: "$37.99",
        imageUrl: "https://spoonacular.com/productImages/447335-312x231.jpg",
        averageRating: 0.9,
        ratingCount: 5.0,
        score: 0.8375,
        link: "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Fpeju-province-merlot-2010%2F133456",
      },
    ],
  },
  instructions:
    "Pat the chickpeas dry with a paper towel and throw them into a food processor along with the garlic.\nPuree until smooth.\nUsing your clean hands incorporate tahini, sriracha, parsley and onion into the chickpea mixture.\nForm mixture into four patties and set aside.\nHeat peanut oil in a large skillet over medium heat.\nOnce the oil begins to shimmer add the patties and cook for three minutes per side or until golden brown.\nRemove from and place in a hamburger bun.\nTop each burger with 2 slices of tomato, 2 slices of cucumber and a dollop of tzatziki.\nServe immediately.",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Pat the chickpeas dry with a paper towel and throw them into a food processor along with the garlic.",
          ingredients: [
            {
              id: 16057,
              name: "chickpeas",
              localizedName: "chickpeas",
              image: "chickpeas.png",
            },
            {
              id: 11215,
              name: "garlic",
              localizedName: "garlic",
              image: "garlic.png",
            },
          ],
          equipment: [
            {
              id: 404771,
              name: "food processor",
              localizedName: "food processor",
              image: "food-processor.png",
            },
            {
              id: 405895,
              name: "paper towels",
              localizedName: "paper towels",
              image: "paper-towels.jpg",
            },
          ],
        },
        {
          number: 2,
          step: "Puree until smooth.",
          ingredients: [],
          equipment: [],
        },
        {
          number: 3,
          step: "Using your clean hands incorporate tahini, sriracha, parsley and onion into the chickpea mixture.",
          ingredients: [
            {
              id: 16057,
              name: "chickpeas",
              localizedName: "chickpeas",
              image: "chickpeas.png",
            },
            {
              id: 1016168,
              name: "sriracha",
              localizedName: "sriracha",
              image: "hot-sauce-or-tabasco.png",
            },
            {
              id: 11297,
              name: "parsley",
              localizedName: "parsley",
              image: "parsley.jpg",
            },
            {
              id: 12698,
              name: "tahini",
              localizedName: "tahini",
              image: "tahini-paste.png",
            },
            {
              id: 11282,
              name: "onion",
              localizedName: "onion",
              image: "brown-onion.png",
            },
          ],
          equipment: [],
        },
        {
          number: 4,
          step: "Form mixture into four patties and set aside.",
          ingredients: [],
          equipment: [],
        },
        {
          number: 5,
          step: "Heat peanut oil in a large skillet over medium heat.",
          ingredients: [
            {
              id: 4042,
              name: "peanut oil",
              localizedName: "peanut oil",
              image: "peanut-oil.jpg",
            },
          ],
          equipment: [
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
        },
        {
          number: 6,
          step: "Once the oil begins to shimmer add the patties and cook for three minutes per side or until golden brown.",
          ingredients: [
            {
              id: 4582,
              name: "cooking oil",
              localizedName: "cooking oil",
              image: "vegetable-oil.jpg",
            },
          ],
          equipment: [],
          length: {
            number: 3,
            unit: "minutes",
          },
        },
        {
          number: 7,
          step: "Remove from and place in a hamburger bun.",
          ingredients: [
            {
              id: 18350,
              name: "hamburger bun",
              localizedName: "hamburger bun",
              image: "hamburger-bun.jpg",
            },
          ],
          equipment: [],
        },
        {
          number: 8,
          step: "Top each burger with 2 slices of tomato, 2 slices of cucumber and a dollop of tzatziki.",
          ingredients: [
            {
              id: 11206,
              name: "cucumber",
              localizedName: "cucumber",
              image: "cucumber.jpg",
            },
            {
              id: 93777,
              name: "tzatziki",
              localizedName: "tzatziki",
              image: "raita-or-tzaziki.png",
            },
            {
              id: 11529,
              name: "tomato",
              localizedName: "tomato",
              image: "tomato.png",
            },
          ],
          equipment: [],
        },
        {
          number: 9,
          step: "Serve immediately.",
          ingredients: [],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl: "https://spoonacular.com/falafel-burger-642539",
};
