export const searchResult = {
  results: [
    {
      id: 631814,
      title: "$50,000 Burger",
      image: "https://spoonacular.com/recipeImages/631814-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 642539,
      title: "Falafel Burger",
      image: "https://spoonacular.com/recipeImages/642539-312x231.png",
      imageType: "png",
    },
    {
      id: 663050,
      title: "Tex-Mex Burger",
      image: "https://spoonacular.com/recipeImages/663050-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 622825,
      title: "Tortilla Burger Loco Vaca",
      image: "https://spoonacular.com/recipeImages/622825-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 663357,
      title: "The Unagi Burger",
      image: "https://spoonacular.com/recipeImages/663357-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 663252,
      title: "The Blarney Burger",
      image: "https://spoonacular.com/recipeImages/663252-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 651190,
      title: "Masala-Tofu Burger",
      image: "https://spoonacular.com/recipeImages/651190-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 663209,
      title: "The Benedict Burger",
      image: "https://spoonacular.com/recipeImages/663209-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 650181,
      title: "Little Italy Burger",
      image: "https://spoonacular.com/recipeImages/650181-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 637631,
      title: "Cheesy Bacon Burger with Spicy Chipotle Aiolo Sauce",
      image: "https://spoonacular.com/recipeImages/637631-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 638771,
      title: "Chipotle-Salsa Burger",
      image: "https://spoonacular.com/recipeImages/638771-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1697575,
      title: "Crispy Chicken Burger",
      image: "https://spoonacular.com/recipeImages/1697575-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 657243,
      title: "Pumpkin Almond Burger Patties",
      image: "https://spoonacular.com/recipeImages/657243-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 650377,
      title: "Low Carb Brunch Burger",
      image: "https://spoonacular.com/recipeImages/650377-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 780000,
      title: "Chicken Avocado Burger (Whole 30, PALEO, & Simple Fit Forty)",
      image: "https://spoonacular.com/recipeImages/780000-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632342,
      title: "An American Beef Burger",
      image: "https://spoonacular.com/recipeImages/632342-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 649141,
      title: "La Bella Italian Turkey Burger",
      image: "https://spoonacular.com/recipeImages/649141-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 775621,
      title: "Gorgonzola & Grilled Peach Burger",
      image: "https://spoonacular.com/recipeImages/775621-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 635345,
      title: "Blue Cheese and Mushroom Turkey Burger",
      image: "https://spoonacular.com/recipeImages/635345-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 801377,
      title: "Chicken Parmesan Patty- Eat As A Burger OR On Pasta",
      image: "https://spoonacular.com/recipeImages/801377-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 664011,
      title: "Turkey Burgers",
      image: "https://spoonacular.com/recipeImages/664011-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 642540,
      title: "Falafel Burgers",
      image: "https://spoonacular.com/recipeImages/642540-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 648303,
      title: "Itty Bitty Burgers",
      image: "https://spoonacular.com/recipeImages/648303-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 635350,
      title: "Blue Cheese Burgers",
      image: "https://spoonacular.com/recipeImages/635350-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 642695,
      title: "Feta Stuffed Burgers",
      image: "https://spoonacular.com/recipeImages/642695-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 650235,
      title: "Loaded Turkey Burgers",
      image: "https://spoonacular.com/recipeImages/650235-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 991010,
      title: "Chicken Ranch Burgers",
      image: "https://spoonacular.com/recipeImages/991010-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 649940,
      title: "Lentil Veggie Burgers",
      image: "https://spoonacular.com/recipeImages/649940-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 649182,
      title: "Lamb and Bacon Burgers",
      image: "https://spoonacular.com/recipeImages/649182-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632300,
      title: "Amazing Chicken Burgers",
      image: "https://spoonacular.com/recipeImages/632300-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1096267,
      title: "Turkey Burgers with Slaw",
      image: "https://spoonacular.com/recipeImages/1096267-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 647296,
      title: "Honey Wheat Hamburger Buns",
      image: "https://spoonacular.com/recipeImages/647296-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 644835,
      title: "Gluten Free Hamburger Buns",
      image: "https://spoonacular.com/recipeImages/644835-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 638566,
      title: "Chili Lime Chicken Burgers",
      image: "https://spoonacular.com/recipeImages/638566-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1487865,
      title: "Easy Cheeseburger Casserole",
      image: "https://spoonacular.com/recipeImages/1487865-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 638497,
      title: "Chickpea and Veggie Burgers",
      image: "https://spoonacular.com/recipeImages/638497-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 637488,
      title: "Chavrie Stuffed Turkey Burgers",
      image: "https://spoonacular.com/recipeImages/637488-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1095755,
      title: "Quinoa and Kidney Bean Burgers",
      image: "https://spoonacular.com/recipeImages/1095755-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 636595,
      title: "Butternut Squash Quinoa Burgers",
      image: "https://spoonacular.com/recipeImages/636595-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1096060,
      title: "Chicken Burgers with Spiced Rub",
      image: "https://spoonacular.com/recipeImages/1096060-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 649195,
      title: "Lamb Burgers With Tzatziki Sauce",
      image: "https://spoonacular.com/recipeImages/649195-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 664929,
      title: "Walnut Lentil Burgers with Tarragon",
      image: "https://spoonacular.com/recipeImages/664929-312x231.png",
      imageType: "png",
    },
    {
      id: 1095894,
      title: "Salmon Amaranth Burgers with Radish Slaw",
      image: "https://spoonacular.com/recipeImages/1095894-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 648663,
      title: "Just Julie’s BBQ Spicy Black Bean Burgers",
      image: "https://spoonacular.com/recipeImages/648663-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 659058,
      title: "Salmon Burgers With Roasted Red Pepper Aioli",
      image: "https://spoonacular.com/recipeImages/659058-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 635059,
      title: "Black Bean and Veggie Burgers with Corn Salsa",
      image: "https://spoonacular.com/recipeImages/635059-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 640266,
      title: "Crab and Shrimp Burgers With Garlic Grits Fries",
      image: "https://spoonacular.com/recipeImages/640266-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 1095682,
      title: "Mini Zucchini Avocado Burgers",
      image: "https://spoonacular.com/recipeImages/1095682-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632874,
      title: "Asian Salmon Burgers With Tangy Ginger Lime Sauce",
      image: "https://spoonacular.com/recipeImages/632874-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 664080,
      title: "Turkey-Spinach Burgers With Sweet Soy-Ginger Sauce",
      image: "https://spoonacular.com/recipeImages/664080-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632502,
      title: "Apple Cheddar Turkey Burgers With Chipotle Yogurt Sauce",
      image: "https://spoonacular.com/recipeImages/632502-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 645608,
      title: "Grilled Turkey Burgers with Roasted Jalapeños and BBQ Sauce",
      image: "https://spoonacular.com/recipeImages/645608-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 638744,
      title: "Chipotle Cheese Stuffed Black Bean Burgers with Avocado Creme",
      image: "https://spoonacular.com/recipeImages/638744-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 645680,
      title:
        "Grilled Chuck Burgers with Extra Sharp Cheddar and Lemon Garlic Aioli",
      image: "https://spoonacular.com/recipeImages/645680-312x231.jpg",
      imageType: "jpg",
    },
  ],
  offset: 0,
  number: 100,
  totalResults: 54,
};

export const recipeInformation = {
  vegetarian: true,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 12,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 9,
  healthScore: 2,
  creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
  license: "CC BY 3.0",
  sourceName: "Foodista",
  pricePerServing: 74.71,
  extendedIngredients: [
    {
      id: 18369,
      aisle: "Baking",
      image: "white-powder.jpg",
      consistency: "SOLID",
      name: "baking powder",
      nameClean: "baking powder",
      original: "1 ½ tsp baking powder",
      originalName: "baking powder",
      amount: 1.5,
      unit: "tsp",
      meta: [],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 18372,
      aisle: "Baking",
      image: "white-powder.jpg",
      consistency: "SOLID",
      name: "baking soda",
      nameClean: "baking soda",
      original: "1 ½ tsp baking soda",
      originalName: "baking soda",
      amount: 1.5,
      unit: "tsp",
      meta: [],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 1230,
      aisle: "Milk, Eggs, Other Dairy",
      image: "buttermilk.jpg",
      consistency: "SOLID",
      name: "buttermilk",
      nameClean: "buttermilk",
      original: "1 ½ cups buttermilk",
      originalName: "buttermilk",
      amount: 1.5,
      unit: "cups",
      meta: [],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 354.882,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 10219334,
      aisle: "Baking",
      image: "raw-brown-sugar.png",
      consistency: "SOLID",
      name: "muscovado sugar",
      nameClean: "muscovado sugar",
      original: "¼ cup Muscovado sugar",
      originalName: "Muscovado sugar",
      amount: 0.25,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 59.147,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 10019908,
      aisle: "Health Foods;Baking",
      image: "raw-brown-sugar.png",
      consistency: "SOLID",
      name: "demerara sugar",
      nameClean: "demerara sugar",
      original: "½ cup Demerara sugar",
      originalName: "Demerara sugar",
      amount: 0.5,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 118.294,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 1123,
      aisle: "Milk, Eggs, Other Dairy",
      image: "egg.png",
      consistency: "SOLID",
      name: "eggs",
      nameClean: "egg",
      original: "3 eggs",
      originalName: "eggs",
      amount: 3.0,
      unit: "",
      meta: [],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 3.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 20081,
      aisle: "Baking",
      image: "flour.png",
      consistency: "SOLID",
      name: "flour",
      nameClean: "wheat flour",
      original: "3 cups all-purpose flour",
      originalName: "all-purpose flour",
      amount: 3.0,
      unit: "cups",
      meta: ["all-purpose"],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 709.764,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 11216,
      aisle: "Produce;Ethnic Foods;Spices and Seasonings",
      image: "ginger.png",
      consistency: "SOLID",
      name: "ginger",
      nameClean: "ginger",
      original: "2 Tbs peeled, grated ginger",
      originalName: "peeled, grated ginger",
      amount: 2.0,
      unit: "Tbs",
      meta: ["grated", "peeled"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "Tbs",
          unitLong: "Tbs",
        },
        metric: {
          amount: 2.0,
          unitShort: "Tbs",
          unitLong: "Tbs",
        },
      },
    },
    {
      id: 1012010,
      aisle: "Spices and Seasonings",
      image: "cinnamon.jpg",
      consistency: "SOLID",
      name: "ground cinnamon",
      nameClean: "ground cinnamon",
      original: "1 ½ tsp ground cinnamon",
      originalName: "ground cinnamon",
      amount: 1.5,
      unit: "tsp",
      meta: [],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 19911,
      aisle: "Cereal",
      image: "maple-syrup.png",
      consistency: "LIQUID",
      name: "maple syrup",
      nameClean: "maple syrup",
      original: "5 Tbs maple syrup or honey",
      originalName: "maple syrup or honey",
      amount: 5.0,
      unit: "Tbs",
      meta: [],
      measures: {
        us: {
          amount: 5.0,
          unitShort: "Tbs",
          unitLong: "Tbs",
        },
        metric: {
          amount: 5.0,
          unitShort: "Tbs",
          unitLong: "Tbs",
        },
      },
    },
    {
      id: 9252,
      aisle: "Produce",
      image: "pears-bosc.jpg",
      consistency: "SOLID",
      name: "pears",
      nameClean: "pear",
      original:
        "4-5 medium to large ripe pears, peeled, cored, and quartered lengthwise",
      originalName:
        "to large ripe pears, peeled, cored, and quartered lengthwise",
      amount: 4.0,
      unit: "",
      meta: ["medium to large", "cored", "ripe", "peeled", "quartered"],
      measures: {
        us: {
          amount: 4.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 4.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 2047,
      aisle: "Spices and Seasonings",
      image: "salt.jpg",
      consistency: "SOLID",
      name: "salt",
      nameClean: "table salt",
      original: "1 cup salt",
      originalName: "salt",
      amount: 1.0,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 236.588,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 1145,
      aisle: "Milk, Eggs, Other Dairy",
      image: "butter-sliced.jpg",
      consistency: "SOLID",
      name: "butter",
      nameClean: "unsalted butter",
      original: "1 stick of unsalted butter, melted",
      originalName: "unsalted butter, melted",
      amount: 1.0,
      unit: "stick",
      meta: ["unsalted", "melted"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "stick",
          unitLong: "stick",
        },
        metric: {
          amount: 1.0,
          unitShort: "stick",
          unitLong: "stick",
        },
      },
    },
  ],
  id: 655455,
  title: "Pear-ginger upside-down cake",
  readyInMinutes: 45,
  servings: 12,
  sourceUrl:
    "http://www.foodista.com/recipe/T7T3XW2K/pear-ginger-upside-down-cake",
  image: "https://spoonacular.com/recipeImages/655455-556x370.jpg",
  imageType: "jpg",
  summary:
    'Need a <b>lacto ovo vegetarian dessert</b>? Pear-ginger upside-down cake could be an awesome recipe to try. This recipe serves 12. One portion of this dish contains approximately <b>6g of protein</b>, <b>10g of fat</b>, and a total of <b>325 calories</b>. For <b>75 cents per serving</b>, this recipe <b>covers 9%</b> of your daily requirements of vitamins and minerals. If you have maple syrup, butter, buttermilk, and a few other ingredients on hand, you can make it. 9 people have tried and liked this recipe. From preparation to the plate, this recipe takes around <b>45 minutes</b>. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 29%</b>. This score is rather bad. Similar recipes include <a href="https://spoonacular.com/recipes/pear-ginger-upside-down-cake-166922">Pear-Ginger Upside-Down Cake</a>, <a href="https://spoonacular.com/recipes/pear-upside-down-ginger-cake-655445">Pear Upside-Down Ginger Cake</a>, and <a href="https://spoonacular.com/recipes/pear-ginger-upside-down-cake-1433475">Pear-ginger upside-down cake</a>.',
  cuisines: [],
  dishTypes: ["dessert"],
  diets: ["lacto ovo vegetarian"],
  occasions: [],
  winePairing: {
    pairedWines: ["cream sherry", "port", "moscato dasti"],
    pairingText:
      "Cake works really well with Cream Sherry, Port, and Moscato d'Asti. A common wine pairing rule is to make sure your wine is sweeter than your food. Delicate desserts go well with Moscato d'Asti, nutty desserts with cream sherry, and caramel or chocolate desserts pair well with port. The NV Solera Cream Sherry with a 4.5 out of 5 star rating seems like a good match. It costs about 17 dollars per bottle.",
    productMatches: [
      {
        id: 428475,
        title: "NV Solera Cream Sherry",
        description:
          "The Solera Cream Sherry has a brilliant amber and deep copper hue. With butterscotch and pecan aromas, the sweet salted nut and brown spice aromas carry a complex caramel accent. A sweet entry leads to a rounded, lush, moderately full-bodied palate with a lengthy, flavorful finish.",
        price: "$16.99",
        imageUrl: "https://spoonacular.com/productImages/428475-312x231.jpg",
        averageRating: 0.9,
        ratingCount: 4.0,
        score: 0.823076923076923,
        link: "https://www.amazon.com/NV-Solera-Cream-Sherry-750/dp/B00HSME8OW?tag=spoonacular-20",
      },
    ],
  },
  instructions:
    "<ol><li>Oil a 9-inch spring form pan, and line the bottom with a 10-inch circle of parchment paper.</li><li>Combine butter, brown sugar, and cinnamon in a medium saucepan. Melt the butter over medium heat for about 1 minute.</li><li>Pour the mixture into the prepared spring form pan, completely coating the parchment paper.</li><li>Place the quartered pears on top of the butter-sugar mixture, lining the pieces up tightly in a decorative circle.</li><li>In a large mixing bowl cream butter (cut into smaller pieces) and brown sugar for 3-5 minutes, until smooth.</li><li>Add the grated ginger, and beat 1 minute more.</li><li>Add the eggs one at a time,making sure that each egg is fully incorporated before adding another.</li><li>Add in the maple syrup or honey and beat to fully mix. The mixture will look as though it is breaking or curdling, but it will come together when the dry ingredients are added.</li><li>In a separate bowl, sift together the flour, baking powder, baking soda, and salt. Whisk to fully combine.</li><li>Alternately add small amounts of flour and buttermilk to the batter, stirring and folding with a rubber spatula until the dry ingredients are just absorbed. Do not overmix the batter.</li><li>Pour and scrape the batter into the pear-lined pan, smoothing the top with a rubber spatula.</li><li>Bake the cake at 325F for about 1 hour and 45 minutes, until a skewer inserted in the cakes centre comes out clean.</li><li>Let the cake cool in the pan for 10 minutes on a wire rack.</li><li>Cover the pan with a serving plate; then carefully invert them together. Release the sides of the pan, and lift it away. Gently lift the pans base off the cake, and peel away the parchment paper.</li><li>Allow the cake to cool, and serve warm.</li></ol>",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Oil a 9-inch spring form pan, and line the bottom with a 10-inch circle of parchment paper.",
          ingredients: [
            {
              id: 4582,
              name: "cooking oil",
              localizedName: "cooking oil",
              image: "vegetable-oil.jpg",
            },
          ],
          equipment: [
            {
              id: 404770,
              name: "baking paper",
              localizedName: "baking paper",
              image: "baking-paper.jpg",
            },
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
        },
        {
          number: 2,
          step: "Combine butter, brown sugar, and cinnamon in a medium saucepan. Melt the butter over medium heat for about 1 minute.",
          ingredients: [
            {
              id: 19334,
              name: "brown sugar",
              localizedName: "brown sugar",
              image: "dark-brown-sugar.png",
            },
            {
              id: 2010,
              name: "cinnamon",
              localizedName: "cinnamon",
              image: "cinnamon.jpg",
            },
            {
              id: 1001,
              name: "butter",
              localizedName: "butter",
              image: "butter-sliced.jpg",
            },
          ],
          equipment: [
            {
              id: 404669,
              name: "sauce pan",
              localizedName: "sauce pan",
              image: "sauce-pan.jpg",
            },
          ],
          length: {
            number: 1,
            unit: "minutes",
          },
        },
        {
          number: 3,
          step: "Pour the mixture into the prepared spring form pan, completely coating the parchment paper.",
          ingredients: [],
          equipment: [
            {
              id: 404770,
              name: "baking paper",
              localizedName: "baking paper",
              image: "baking-paper.jpg",
            },
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
        },
        {
          number: 4,
          step: "Place the quartered pears on top of the butter-sugar mixture, lining the pieces up tightly in a decorative circle.In a large mixing bowl cream butter (cut into smaller pieces) and brown sugar for 3-5 minutes, until smooth.",
          ingredients: [
            {
              id: 19334,
              name: "brown sugar",
              localizedName: "brown sugar",
              image: "dark-brown-sugar.png",
            },
            {
              id: 1001,
              name: "butter",
              localizedName: "butter",
              image: "butter-sliced.jpg",
            },
            {
              id: 1053,
              name: "cream",
              localizedName: "cream",
              image: "fluid-cream.jpg",
            },
            {
              id: 9252,
              name: "pear",
              localizedName: "pear",
              image: "pears-bosc.jpg",
            },
            {
              id: 19335,
              name: "sugar",
              localizedName: "sugar",
              image: "sugar-in-bowl.png",
            },
          ],
          equipment: [
            {
              id: 405907,
              name: "mixing bowl",
              localizedName: "mixing bowl",
              image: "mixing-bowl.jpg",
            },
          ],
          length: {
            number: 5,
            unit: "minutes",
          },
        },
        {
          number: 5,
          step: "Add the grated ginger, and beat 1 minute more.",
          ingredients: [
            {
              id: 11216,
              name: "ginger",
              localizedName: "ginger",
              image: "ginger.png",
            },
          ],
          equipment: [],
          length: {
            number: 1,
            unit: "minutes",
          },
        },
        {
          number: 6,
          step: "Add the eggs one at a time,making sure that each egg is fully incorporated before adding another.",
          ingredients: [
            {
              id: 1123,
              name: "egg",
              localizedName: "egg",
              image: "egg.png",
            },
          ],
          equipment: [],
        },
        {
          number: 7,
          step: "Add in the maple syrup or honey and beat to fully mix. The mixture will look as though it is breaking or curdling, but it will come together when the dry ingredients are added.In a separate bowl, sift together the flour, baking powder, baking soda, and salt.",
          ingredients: [
            {
              id: 18369,
              name: "baking powder",
              localizedName: "baking powder",
              image: "white-powder.jpg",
            },
            {
              id: 18372,
              name: "baking soda",
              localizedName: "baking soda",
              image: "white-powder.jpg",
            },
            {
              id: 19911,
              name: "maple syrup",
              localizedName: "maple syrup",
              image: "maple-syrup.png",
            },
            {
              id: 20081,
              name: "all purpose flour",
              localizedName: "all purpose flour",
              image: "flour.png",
            },
            {
              id: 19296,
              name: "honey",
              localizedName: "honey",
              image: "honey.png",
            },
            {
              id: 2047,
              name: "salt",
              localizedName: "salt",
              image: "salt.jpg",
            },
          ],
          equipment: [
            {
              id: 404783,
              name: "bowl",
              localizedName: "bowl",
              image: "bowl.jpg",
            },
          ],
        },
        {
          number: 8,
          step: "Whisk to fully combine.Alternately add small amounts of flour and buttermilk to the batter, stirring and folding with a rubber spatula until the dry ingredients are just absorbed. Do not overmix the batter.",
          ingredients: [
            {
              id: 1230,
              name: "buttermilk",
              localizedName: "buttermilk",
              image: "buttermilk.jpg",
            },
            {
              id: 20081,
              name: "all purpose flour",
              localizedName: "all purpose flour",
              image: "flour.png",
            },
          ],
          equipment: [
            {
              id: 404642,
              name: "spatula",
              localizedName: "spatula",
              image: "spatula-or-turner.jpg",
            },
            {
              id: 404661,
              name: "whisk",
              localizedName: "whisk",
              image: "whisk.png",
            },
          ],
        },
        {
          number: 9,
          step: "Pour and scrape the batter into the pear-lined pan, smoothing the top with a rubber spatula.",
          ingredients: [
            {
              id: 9252,
              name: "pear",
              localizedName: "pear",
              image: "pears-bosc.jpg",
            },
          ],
          equipment: [
            {
              id: 404642,
              name: "spatula",
              localizedName: "spatula",
              image: "spatula-or-turner.jpg",
            },
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
        },
        {
          number: 10,
          step: "Bake the cake at 325F for about 1 hour and 45 minutes, until a skewer inserted in the cakes centre comes out clean.",
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: "oven",
              localizedName: "oven",
              image: "oven.jpg",
              temperature: {
                number: 325.0,
                unit: "Fahrenheit",
              },
            },
            {
              id: 3065,
              name: "skewers",
              localizedName: "skewers",
              image: "wooden-skewers.jpg",
            },
          ],
          length: {
            number: 105,
            unit: "minutes",
          },
        },
        {
          number: 11,
          step: "Let the cake cool in the pan for 10 minutes on a wire rack.Cover the pan with a serving plate; then carefully invert them together. Release the sides of the pan, and lift it away. Gently lift the pans base off the cake, and peel away the parchment paper.Allow the cake to cool, and serve warm.",
          ingredients: [
            {
              id: 0,
              name: "base",
              localizedName: "base",
              image: "",
            },
          ],
          equipment: [
            {
              id: 404770,
              name: "baking paper",
              localizedName: "baking paper",
              image: "baking-paper.jpg",
            },
            {
              id: 405900,
              name: "wire rack",
              localizedName: "wire rack",
              image: "wire-rack.jpg",
            },
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
          length: {
            number: 10,
            unit: "minutes",
          },
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl:
    "https://spoonacular.com/pear-ginger-upside-down-cake-655455",
};